#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : htslib
Version  : 1.10.1
Release  : 1
URL      : https://github.com/samtools/htslib/releases/download/1.10.1/htslib-1.10.1.tar.bz2
Source0  : https://github.com/samtools/htslib/releases/download/1.10.1/htslib-1.10.1.tar.bz2
Summary  : C library for high-throughput sequencing data formats
Group    : Development/Tools
License  : BSD-3-Clause
Requires: htslib-bin = %{version}-%{release}
Requires: htslib-lib = %{version}-%{release}
Requires: htslib-license = %{version}-%{release}
Requires: htslib-man = %{version}-%{release}
BuildRequires : bzip2-dev
BuildRequires : curl-dev
BuildRequires : pkgconfig(zlib)
BuildRequires : xz-dev

%description
HTSlib is an implementation of a unified C library for accessing common file
formats, such as SAM, CRAM, VCF, and BCF, used for high-throughput sequencing
data.  It is the core library used by samtools and bcftools.

%package bin
Summary: bin components for the htslib package.
Group: Binaries
Requires: htslib-license = %{version}-%{release}

%description bin
bin components for the htslib package.


%package dev
Summary: dev components for the htslib package.
Group: Development
Requires: htslib-lib = %{version}-%{release}
Requires: htslib-bin = %{version}-%{release}
Provides: htslib-devel = %{version}-%{release}
Requires: htslib = %{version}-%{release}

%description dev
dev components for the htslib package.


%package lib
Summary: lib components for the htslib package.
Group: Libraries
Requires: htslib-license = %{version}-%{release}

%description lib
lib components for the htslib package.


%package license
Summary: license components for the htslib package.
Group: Default

%description license
license components for the htslib package.


%package man
Summary: man components for the htslib package.
Group: Default

%description man
man components for the htslib package.


%prep
%setup -q -n htslib-1.10.1
cd %{_builddir}/htslib-1.10.1

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1576692041
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
export CFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=4 "
export FCFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=4 "
export FFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=4 "
export CXXFLAGS="$CXXFLAGS -O3 -ffat-lto-objects -flto=4 "
%configure --disable-static
make  %{?_smp_mflags}

%install
export SOURCE_DATE_EPOCH=1576692041
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/htslib
cp %{_builddir}/htslib-1.10.1/LICENSE %{buildroot}/usr/share/package-licenses/htslib/6a9fda1ee5bdca4863a27d95d7b94669a27259fa
%make_install

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/usr/bin/bgzip
/usr/bin/htsfile
/usr/bin/tabix

%files dev
%defattr(-,root,root,-)
/usr/include/htslib/bgzf.h
/usr/include/htslib/cram.h
/usr/include/htslib/faidx.h
/usr/include/htslib/hfile.h
/usr/include/htslib/hts.h
/usr/include/htslib/hts_defs.h
/usr/include/htslib/hts_endian.h
/usr/include/htslib/hts_log.h
/usr/include/htslib/hts_os.h
/usr/include/htslib/kbitset.h
/usr/include/htslib/kfunc.h
/usr/include/htslib/khash.h
/usr/include/htslib/khash_str2int.h
/usr/include/htslib/klist.h
/usr/include/htslib/knetfile.h
/usr/include/htslib/kseq.h
/usr/include/htslib/ksort.h
/usr/include/htslib/kstring.h
/usr/include/htslib/regidx.h
/usr/include/htslib/sam.h
/usr/include/htslib/synced_bcf_reader.h
/usr/include/htslib/tbx.h
/usr/include/htslib/thread_pool.h
/usr/include/htslib/vcf.h
/usr/include/htslib/vcf_sweep.h
/usr/include/htslib/vcfutils.h
/usr/lib64/libhts.so
/usr/lib64/pkgconfig/htslib.pc

%files lib
%defattr(-,root,root,-)
/usr/lib64/libhts.so.1.10.1
/usr/lib64/libhts.so.3

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/htslib/6a9fda1ee5bdca4863a27d95d7b94669a27259fa

%files man
%defattr(0644,root,root,0755)
/usr/share/man/man1/bgzip.1
/usr/share/man/man1/htsfile.1
/usr/share/man/man1/tabix.1
/usr/share/man/man5/faidx.5
/usr/share/man/man5/sam.5
/usr/share/man/man5/vcf.5
/usr/share/man/man7/htslib-s3-plugin.7
